### ISSUE TITLE
Create CRUD routes for Users

### ISSUE THREAD

**Issue by joshghent** [esfiddle/api#15]
As documented in #1 - create the POST, GET, PUT and DELETE endpoints for users.
Make sure the data goes into mongodb and cannot be retrieved unless you are authenticated.

This need to interact with our frontend which will login with PassportJS

**Comment by mct-dev** [comment]
I'll give this one a shot if you guys don't mind 😄

**Comment by distalx** [comment]
Hi! @joshghent 
I'd like to give it a try. I'm familiar with express and passport.js, but haven't used typescript in real-project. So that's the part that I'm nervous about.

**Comment by joshghent** [comment]
Hey @distalx - thanks for offering to contribute. No worries about not having used Typescript before, myself, @collinmesser or @anagabriel42 will be happy to help 👍
